# this is my Make file I don't know if it works. 


# Variables to control Makefile operations



CXX = g++	
CXXFLAGS = -std=c++0X


main: main.cpp Queue.h bPTree.h node.h shared.h	

$(CXX)	$(CXXFLAGS) -o main main.o 
