# this is my Make file I don't know if it works. 


# Variables to control Makefile operations



CXX = g++	
CXXFLAGS = -t


main: main.cpp Queue.h bPTree.h node.h shared.h	

$(CXX)	$(CXXFLAGS) -o main main.o Queue.o bPTree.o node.o shared.o